### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by Mx74** [FreeCAD/pivy#33] opened 2018-03-26 14:53 UTC
Hello,

I have to install pivy for a Freecad workbench, but I have some trouble:
Ubuntu 17.10, fresh install:
I install freecad-daily.
Then:
pip install https://github.com/FreeCAD/pivy/archive/master.zip gives the following error:

` ~~~ HISSSSSSSSSS ~~~
                               Welcome to Pivy 0.6.3!
                     Building Pivy has never been so much fun!
    
    
    Platform...linux2
    Python version...2.7.14
    Checking for swig...
    not found.
    Checking for swig3.0...
    not found.
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-JRYOeQ-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-oYhwod-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-JRYOeQ-build/
`

Obviously, swig is missing, I install it, but then:

`Installing collected packages: Pivy
  Running setup.py install for Pivy ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-tPN9u6-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-Cn1XBM-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    running install
    running build
    
                                _____
                            .-'`     '.
                         __/  __       \
                        /  \ /  \       |    ___
                       | /`\| /`\|      | .-'  /^\/^\
                       | \(/| \(/|      |/     |) |)|
                      .-\__/ \__/       |      \_/\_/__..._
              _...---'-.                /   _              '.
             /,      ,             \   '|  `\                \
            | ))     ))           /`|   \    `.       /)  /) |
            | `      `          .'       |     `-._         /
            \                 .'         |     ,_  `--....-'
             `.           __.' ,         |     / /`'''`
               `'-.____.-' /  /,         |    / /
                   `. `-.-` .'  \        /   / |
                     `-.__.'|    \      |   |  |-.
                        _.._|     |     /   |  |  `'.
                  .-''``    |     |     |   /  |     `-.
               .'`         /      /     /  |   |        '.
             /`           /      /     |   /   |\         \
            /            |      |      |   |   /\          |
           ||            |      /      |   /     '.        |
           |\            \      |      /   |       '.      /
           \ `.           '.    /      |    \        '---'/
            \  '.           `-./        \    '.          /
             '.  `'.            `-._     '.__  '-._____.'--'''''--.
               '-.  `'--._          `.__     `';----`              \
                  `-.     `-.          `.''```                     ;
                     `'-..,_ `-.         `'-.                     /
                            '.  '.           '.                 .'
    
    
                                ~~~ HISSSSSSSSSS ~~~
                               Welcome to Pivy 0.6.3!
                     Building Pivy has never been so much fun!
    
    
    Platform...linux2
    Python version...2.7.14
    Checking for swig...
    '/usr/bin/swig'
    Checking for SWIG version...
    3.0.10
    calling: cmake .
    error: [Errno 2] No such file or directory
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-tPN9u6-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-Cn1XBM-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-tPN9u6-build/
`

**Comment by looooo** [comment] 2018-03-26 15:57
thanks for reporting. I guess the problem is that you are running the install not from the source dir. I pushed a fix for this issue. Maybe you can try.

**Comment by Mx74** [comment] 2018-03-26 16:15
I tried right now, and the error message changed:

calling: cmake /tmp/pip-FcTt6n-build
    error: [Errno 2] No such file or directory
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-FcTt6n-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-DRVzGy-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-FcTt6n-build/

**Comment by Mx74** [comment] 2018-03-26 16:16
what do you mean by 

> also note that coin has to be build with cmake.

?

**Comment by looooo** [comment] 2018-03-26 16:36
maybe cmake is missing:
```
sudo apt-get install cmake
```

**Comment by looooo** [comment] 2018-03-26 16:39
regarding coin: coin3d offers cmake as build-system. To support qt5 I updated pivy to work with coin build with cmake. Therefor it's not possible anymore to build pivy with older versions of coin.

If you don' care about qt5 /cmake you can try the following:
```
pip install https://github.com/FreeCAD/pivy/archive/0.6.2.tar.gz
```

**Closed** 2018-05-07 05:38 UTC
